services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: redis_ecommerce
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    restart: always

volumes:
  mongodb_data:
